### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by iantearle** [RomanSixty/Feed-on-Feeds#16]
What is the consensus of theming? Providing a theme folder to contain:

header.php
items.php
render.php
footer.php

I have already ported the JS to jquery. Just working on the latest functions.

**Comment by RomanSixty** [comment]
Closing because there are no updates for 5 years.

Concerning mobile use I recently made the UI responsive (starting with b3e45c680d4ae776d455bc095f6eb5ed0b9832b6). Also all JS has been ported from prototype.js to vanilla javascript (from e1dc3a128ccea389e85de26647e221ae49a29790), so there's no need for jQuery anymore either.
